kind: ConfigMap
apiVersion: v1
metadata:
  namespace: collectd
  name: collectd-config

data:

  node-collectd.conf: |-
    #Hostname "<hostname_goes_here>"
    #Sets the hostname that identifies a host. If you omit this setting, 
    #the hostname will be determined using the gethostname(2) system call.
    #
    Interval "10"
    LoadPlugin contextswitch
    LoadPlugin cpu
    LoadPlugin cpufreq
    LoadPlugin df
    LoadPlugin disk
    LoadPlugin ethstat
    LoadPlugin interface
    LoadPlugin ipc
    LoadPlugin irq
    LoadPlugin load
    LoadPlugin memory
    LoadPlugin numa
    LoadPlugin processes
    LoadPlugin swap
    #LoadPlugin turbostat
    LoadPlugin uptime
    LoadPlugin intel_pmu
    LoadPlugin intel_rdt
    LoadPlugin network
    #LoadPlugin write_prometheus
    <Plugin intel_pmu>
      ReportHardwareCacheEvents true
      ReportKernelPMUEvents true
      ReportSoftwareEvents true
      EventList "/var/cache/pmu/GenuineIntel-6-2D-core.json"
      HardwareEvents "L2_RQSTS.CODE_RD_HIT,L2_RQSTS.CODE_RD_MISS" "L2_RQSTS.ALL_CODE_RD"
      Cores "[0-4]"
    </Plugin>
    <LoadPlugin intel_rdt>
      Interval 1
    </LoadPlugin>
    <Plugin intel_rdt>
      Cores "0-12"
    </Plugin>
    <Plugin network>
        Server "<destination_host_goes_here>" "25826" #InfluxDB
    </Plugin>
    #<Plugin "write_prometheus">
    #  Port "9103"
    #</Plugin>

    #Last line (collectd requires ‘\n’ at the last line)
